version: '3.8'

services:
  backend:
    build: ./backend
    container_name: shoemarknet-backend
    restart: unless-stopped
    env_file: ./.env
    ports:
      - ${BACKEND_LOCAL_PORT}:5000
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - NODE_ENV=development
      - FRONTEND_URL=http://localhost:${FRONTEND_LOCAL_PORT}
    networks:
      - shoemarknet-network
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: ./frontend
    container_name: shoemarknet-frontend
    restart: unless-stopped
    ports:
      - ${FRONTEND_LOCAL_PORT}:5173
    environment:
      - VITE_API_URL=http://localhost:${BACKEND_LOCAL_PORT}
    depends_on:
      - backend
    networks:
      - shoemarknet-network
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  shoemarknet-network:
    driver: bridge
